### ISSUE TITLE
已经解决

### ISSUE THREAD

**Issue by ghost** [yjh0410/FCOS_PyTorch#3]
刚刚提问完我又来了QAQ
运行tran_voc.py 以后 一直卡在这个界面 也没有显示在训练的数据，该如何解决？
（环境18.04/py37/pytoch1.1)
![2020-04-22 17-41-17 的屏幕截图](https://user-images.githubusercontent.com/32098986/79960988-0c693f00-84c1-11ea-966f-53b5cf9c772f.png)

**Comment by yjh0410** [comment]
我重写了下train_voc.py代码，你再试一试

**Comment by yjh0410** [comment]
![image](https://user-images.githubusercontent.com/35093017/79968182-59014a00-84c2-11ea-8d47-449a779ee3f7.png)
最新的模型在我这边是可以train的

**Comment by ghost** [comment]
gooood job ~~~~
